name: deploy site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set Node.js
      uses: actions/setup-node@master
      with:
        node-version: 10.x

    - name: Install dependencies
      run: npm i
    
    - name: Login e-mail
      run: git config --global user.email "raonidemarchi@gmail.com"
    
    - name: Login name
      run: git config --global user.name "raonidemarchi"

    - name: Deploy
      run: npm run deploy
      env:
        DEPLOY_KEY: ${{ secrets.deploy_key }}
